name = "EnzymePrecompilationTest"
uuid = "f873719c-969b-40aa-ba1b-e801ab8a9d64"
authors = ["Simone Surace <simone.surace@artificialy.com>"]
version = "0.1.0"

[deps]
Enzyme = "7da242da-08ed-463a-9acd-ee780be4f1d9"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
